# inherit_from: ./.rubocop_todo.yml

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Metrics/CyclomaticComplexity:
  Max: 7
